hugoblox:
  schema: "2.0"
  identity:
    name: Jeff XING
    type: person
    tagline: Sensing & Understanding World by Vision
    description: Jeff XING is currently an algorithm engineer in computer vision Intel since 2020. He works in ISP, 3D vision,  MvLLMs...
  theme:
    mode: system
    pack: minimal
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
